default:
  - serve

serve:
  - clean:server
  - jade
  - sass
  - coffee
  - autoprefixer
  - connect:server
  - watch

build:
  - clean:build
  - jade
  - sass
  - autoprefixer
  - copy:dist
  - useminPrepare
  - concat
  - cssmin
  - uglify
  - imagemin
  - svgmin
  - usemin

deploy:
  - build
  - githubPages
